name: Build

on: 
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Celeste Loader
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1

      - name: Initialize and update submodules
        run: |
          git submodule update --init --recursive

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Check if package.json exists
        run: |
          if [ ! -f package.json ]; then
            echo "package.json not found, skipping pnpm install."
            exit 0
          fi

      - name: Install dependencies
        if: hashFiles('package.json') != ''
        run: pnpm install --no-frozen-lockfile

      - name: Setup Dotnet 
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.102'

      - name: Install mono
        run: sudo apt-get install mono-devel

      - name: Debug - Check directory structure
        run: ls -R

      - name: Ensure loader directory exists
        run: |
          if [ ! -d loader ]; then
            echo "Error: loader directory not found!"
            exit 1
          fi

      - name: Build Csproj
        run: |
          cd loader && dotnet workload restore && cd ..
          if [ ! -d Content ]; then
            echo "Warning: Content directory not found! Skipping Content-related operations."
          fi
          make publish || echo "Make publish failed, please check logs."

      - uses: actions/upload-artifact@v4
        with:
          name: webleste-loader
          path: frontend/dist/
          compression-level: 6
